
---
title: "Telework, Inequality, and Public Opinion During COVID-19 in France"
date: 2021-11-03
categories: [policy, seminar, covid, france]
---

By Ebenezer Makinde, Natascha Schoepl, Sonia Yazidi

A year on from the COVID-19 crisis, students of the School of Public Affairs reflected on its effects on French society, with expert insights from Dr. Ettore Recchi and Dr. Emanuele Ferragina. Dr. Recchi and Dr. Ferragina recently worked on the pandemic with a team of researchers at the Observatoire Sociologique du Changement. The policy seminar was moderated by students from the Politics & Public Policy stream, who shared their key takeaways.

This policy seminar was the first of four bilingual seminars aimed at giving students direct insight into the sociological effects of a global health crisis. The speakers presented their work on social inequalities and transformations during the COVID-19 crisis, as well as the effects of lockdown on society, especially in France. In their project, *Coping with Covid (COCO): The Experience of Lockdown in the French Population*, Dr. Recchi and Dr. Ferragina conducted quantitative research using a pre-existing panel of participants and survey data to examine how the pandemic affected social relationships and lifestyles.

[Read Full Article](https://www.sciencespo.fr/ecole-affaires-publiques/en/news/what-does-covid-19-do-society/)




