---
title: ""
page-title: false
---

### Ebenezer O. Makinde 
**PhD Candidate in Political Science**  
**[Tulane University](https://liberalarts.tulane.edu/political-science)**  


::: {.contact-box}

### Contact & Profiles

- ✉️ [Email](mailto:emakinde@tulane.edu)  
- 💼 [LinkedIn](https://www.linkedin.com/in/ebenezermakinde/)  
- 💻 [GitHub](https://github.com/Ebenad)  
- 📚 [Google Scholar](https://scholar.google.com/citations?user=L7VuBQUAAAAJ&hl=en)

:::


## Welcome!

I am a PhD candidate in Political Science at [*Tulane University*](https://liberalarts.tulane.edu/political-science/people/graduate-students/ebenezer-o-makinde). My ongoing dissertation project examines the political consequences of anti-corruption politicization. I study how governments use anti-corruption agencies (ACAs) strategically—sometimes to genuinely reduce corruption, and other times, to punish rivals and protect allies—and how these actions shape the behavior of political elites and citizens.

My broader research agenda spans comparative politics, African political economy, and public policy, with a regional focus on Nigeria and Africa. I work extensively with original and administrative data on corruption prosecutions, public opinion, political behavior, and governance outcomes, and I mostly use quantitative methods, causal inference tools, and mixed-methods approaches (including interviews, archival data, survey experiments).

In my other ongoing projects, I am examining the political economy of corruption prosecution outcomes in Nigeria, African public opinion on great-power competition in Africa, and government–NGO relations in Nigeria. My works have been published in peer-reviewed journals including [*Policy & Internet*](https://onlinelibrary.wiley.com/doi/full/10.1002/poi3.416), [*Protest*](https://brill.com/view/journals/prot/4/1/article-p5_002.xml?ebody=Abstract%2FExcerpt), [*World Journal of Advanced Research and Reviews*](https://wjarr.com/content/harnessing-artificial-intelligence-optimize-financial-technologies-achieving-sustainable), and [*GSC Advanced Research and Reviews*](https://gsconlinepress.com/journals/gscarr/content/leveraging-artificial-intelligence-enhanced-tax-fraud-detection-modern-fiscal-systems).

Before graduate school, I held policy and data analytics roles in France, South Africa (remote), and Nigeria, including positions at SCOR Reinsurance and the African Leadership Academy. These experiences continue to inform my interest in evidence-based public policy and the design of institutions that promote government accountability and good governance.








