---
title: ""
page-title: false
---


# Working Papers

### 1. **Who Gets Convicted? The Political Economy of Corruption Prosecution Outcomes in Nigeria**  

This paper studies the determinants of outcomes of corruption prosecution using original data on more than two decades of corruption prosecution cases in Nigeria. I assess how the financial resources available to the defendants (operationalized by the monetary value of the funds allegedly stolen or misappropriated by the defendants) and their socio-economic standings influence whether they are convicted, acquitted, or have their cases stalled.

---

### 2. **Anti-corruption or Weaponization? The Politics of Anti-Corruption Prosecution in Nigeria**  

Anti-corruption efforts are often presented as impartial actions designed to promote accountability and dis-incentivize corruption. In practice, however, they can be politi- cized and selectively enforced to serve partisan ends. This paper provides systematic evidence of such dynamics in Nigeria. Drawing on an original dataset of corruption allegations, investigations, and prosecutions involving high-level public officials in Nigeria, I examine how party affiliation and ties to the ruling president influence the decision on who gets prosecuted and the outcomes of prosecutions.
